# Generated by Django 4.0.2 on 2022-02-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='avatar.png', upload_to='student/')),
                ('category', models.CharField(choices=[('1', 'Tecnology'), ('2', 'Social'), ('3', 'Travel'), ('4', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('1', 'Draft'), ('2', 'View')], max_length=50)),
            ],
        ),
    ]
