# Generated by Django 4.0.2 on 2022-02-10 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
