# Generated by Django 4.0.2 on 2022-02-10 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_data_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
