# Generated by Django 4.0.2 on 2022-02-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
