# Generated by Django 4.0.2 on 2022-02-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='blogs/'),
        ),
    ]
